// components/Footer.vue
<template>
  <footer class="bg-gray-900 text-gray-400 py-12 border-t border-gray-800">
    <div class="container-custom">
      <div class="flex flex-col md:flex-row items-center justify-between gap-6">
        <p class="text-sm">
          © {{ currentYear }} Marc Trösken. All rights reserved.
        </p>
        
        <div class="flex items-center gap-6">
          <a 
            v-for="social in socials" 
            :key="social.name"
            :href="social.url" 
            target="_blank"
            rel="noopener noreferrer"
            class="hover:text-white transition-colors"
            :aria-label="social.name"
          >
            {{ social.name }}
          </a>
        </div>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
const currentYear = new Date().getFullYear()

const socials = [
  { name: 'LinkedIn', url: 'https://linkedin.com/in/marc-troesken' },
  { name: 'GitHub', url: 'https://github.com/MarcTroesken' },
]
</script>

// src/components/Footer.tsx
const Footer = () => {
  return (
    <footer className="py-8 px-4 border-t border-border/50">
      <div className="container mx-auto max-w-6xl">
        <div className="flex flex-col md:flex-row justify-between items-center gap-4">
          <p className="text-muted-foreground text-sm">
            © {new Date().getFullYear()} Marc Trösken. Built with React & Tailwind CSS.
          </p>
          <div className="flex gap-6 text-sm text-muted-foreground">
            <a 
              href="https://github.com/marctroesken" 
              target="_blank" 
              rel="noopener noreferrer"
              className="hover:text-accent transition-colors"
            >
              GitHub
            </a>
            <a 
              href="mailto:m.troesken@mail.de"
              className="hover:text-accent transition-colors"
            >
              Email
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
